// <auto-generated />
using ExemploLibrary.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ExemploLibrary.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180419141430_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExemploLibrary.Entidades.Categoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ExemploLibrary.Entidades.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PessoaId");

                    b.Property<long?>("PessoaId1");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.HasIndex("PessoaId1")
                        .IsUnique()
                        .HasFilter("[PessoaId1] IS NOT NULL");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ExemploLibrary.Entidades.Contato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<string>("Telefone");

                    b.HasKey("Id");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("ExemploLibrary.Entidades.Empregado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PessoaId");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.ToTable("Empregados");
                });

            modelBuilder.Entity("ExemploLibrary.Entidades.Etiqueta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Etiquetas");
                });

            modelBuilder.Entity("ExemploLibrary.Entidades.Gerente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PessoaId");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.ToTable("Gerentes");
                });

            modelBuilder.Entity("ExemploLibrary.Entidades.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("EmpregadoId");

                    b.Property<long?>("GerenteId");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("EmpregadoId")
                        .IsUnique()
                        .HasFilter("[EmpregadoId] IS NOT NULL");

                    b.HasIndex("GerenteId")
                        .IsUnique()
                        .HasFilter("[GerenteId] IS NOT NULL");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("ExemploLibrary.Entidades.Produto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoriaId");

                    b.Property<long?>("CategoriaId1");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId1");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ExemploLibrary.Entidades.ProdutoEtiqueta", b =>
                {
                    b.Property<int>("ProdutoId");

                    b.Property<int>("EtiquetaId");

                    b.Property<long?>("EtiquetaId1");

                    b.Property<long?>("ProdutoId1");

                    b.HasKey("ProdutoId", "EtiquetaId");

                    b.HasIndex("EtiquetaId1");

                    b.HasIndex("ProdutoId1");

                    b.ToTable("ProdutosEtiquetas");
                });

            modelBuilder.Entity("ExemploLibrary.Entidades.Cliente", b =>
                {
                    b.HasOne("ExemploLibrary.Entidades.Pessoa", "Pessoa")
                        .WithOne("Cliente")
                        .HasForeignKey("ExemploLibrary.Entidades.Cliente", "PessoaId1");
                });

            modelBuilder.Entity("ExemploLibrary.Entidades.Pessoa", b =>
                {
                    b.HasOne("ExemploLibrary.Entidades.Empregado", "Empregado")
                        .WithOne("Pessoa")
                        .HasForeignKey("ExemploLibrary.Entidades.Pessoa", "EmpregadoId");

                    b.HasOne("ExemploLibrary.Entidades.Gerente", "Gerente")
                        .WithOne("Pessoa")
                        .HasForeignKey("ExemploLibrary.Entidades.Pessoa", "GerenteId");
                });

            modelBuilder.Entity("ExemploLibrary.Entidades.Produto", b =>
                {
                    b.HasOne("ExemploLibrary.Entidades.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId1");
                });

            modelBuilder.Entity("ExemploLibrary.Entidades.ProdutoEtiqueta", b =>
                {
                    b.HasOne("ExemploLibrary.Entidades.Etiqueta", "Etiqueta")
                        .WithMany("ProdutoEtiqueta")
                        .HasForeignKey("EtiquetaId1");

                    b.HasOne("ExemploLibrary.Entidades.Produto", "Produto")
                        .WithMany("ProdutosEtiquetas")
                        .HasForeignKey("ProdutoId1");
                });
#pragma warning restore 612, 618
        }
    }
}
